cookie:
  expiry_days: 5
  key: 8fbe4bca74b76f2d843a33e69934df8b75a47271291759857df2a370ef9ec0d4
  name: auth_cookie
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin
      password: $2b$12$frGg4MbImhLtzoXddGbVU.S63tOukFNVC6sXmNdOQFjqRewdHPxnW
    user:
      email: user@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: user
      password: $2b$12$ui/4UG9RROoiCJ8n89ZnQOGVY33JlRYrUyZZGjKzbAZtIWqOVv5Y.
    user2:
      email: user2@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: user two
      password: $2b$12$DtDhDhd9jGq7BORJHQ/M/uJZC8pHqG.MQ648P7PshSe9w84PwYkDi
    user3:
      email: user3@gmail.com
      logged_in: false
      name: user three
      password: $2b$12$d825RNSleij5uwbnwPm8IePwjAqwoL6NcwBYK5UBTyCKa3k/ugl2O
pre-authorized:
  emails: null
