cookie:
  expiry_days: 5
  key: 8fbe4bca74b76f2d843a33e69934df8b75a47271291759857df2a370ef9ec0d4
  name: auth_cookie
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      logged_in: false
      name: Admin
      password: $2b$12$frGg4MbImhLtzoXddGbVU.S63tOukFNVC6sXmNdOQFjqRewdHPxnW
    user:
      email: user@gmail.com
      logged_in: false
      name: user
      password: $2b$12$ui/4UG9RROoiCJ8n89ZnQOGVY33JlRYrUyZZGjKzbAZtIWqOVv5Y.
pre-authorized:
  emails: null
